### ISSUE TITLE
How to use with puppeteer-core?

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [smooth-code/jest-puppeteer#126]
```Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/dmitry/markup-test/xstartup/node_modules/jest-environment-puppeteer/lib/global.js:21:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by neoziro** [comment]
I am sorry but I can't help you without information, please [submit a correct bug report](https://github.com/smooth-code/jest-puppeteer/issues/new?template=bug.md).
