### ISSUE TITLE
Jest --watch fails to reload

### ISSUE THREAD

**Issue by dmnsgn** [smooth-code/jest-puppeteer#181]
## 🐛 Bug Report

jest-puppeteer crashes on first reload when running `jest --watch`.

## To Reproduce

1. Run `jest --no-cache --watch` (happens with or without `--no-cache`)
2. Wait for tests to pass
3. Change the test.js file or press enter in the terminal (both running the test suite again)
4. `jest-puppeteer` process crash. See error below:

```bash
DevTools listening on ws://127.0.0.1:54958/devtools/browser/e99c5bd8-a51f-44aa-bcc2-9066610c8d7e

Jest dev-server output:
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Transform.Writable.write (_stream_writable.js:296:5)
    at Socket.ondata (_stream_readable.js:693:20)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at Transform.onerror (_stream_readable.js:717:7)
    at Transform.emit (events.js:188:13)
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at writeAfterEnd (_stream_writable.js:250:3)
    at Transform.Writable.write (_stream_writable.js:296:5)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:269:11)
```

## Expected behavior

Tests to be ran again indefinitely without crash.

```bash
## System:
 - OS: macOS 10.14.2
 - CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
 - Memory: 370.26 MB / 8.00 GB
 - Shell: 4.4.19 - /usr/local/bin/bash
## Binaries:
 - Node: 11.6.0 - /usr/local/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 6.5.0-next.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - jest-puppeteer: ^3.7.0 => 3.7.0
```

**Comment by dmnsgn** [comment]
Same error with v3.8.0 but setting `debug: true` for the server options in the config seems to fix it.

**Comment by xiaoyuhen** [comment]
hi, @dmnsgn , The new version has not been released yet. 
If you want to use it as soon as possible, you can use the following method.
```
yarn add  git+ssh://git@github.com/smooth-code/jest-puppeteer.git
```
