### ISSUE TITLE
Cannot find module 'jest-puppeteer'

### ISSUE THREAD

**Issue by R1ZEN** [smooth-code/jest-puppeteer#205]
## 🐛 Bug Report

Can not resolve jest-puppeteer  **preset path** for external packages.

## To Reproduce

Create a structure like:
```
reproduce_folder/
  my_package/
    package.json
  package.json
  jest.config.js
  GooglePage.e2e.test.js
```

Move to `my_package` directory and execute:
```sh
$ npm i jest-puppeteer puppeteer
```

Move to `root` directory and execute:
```sh
$ npm i jest file:my_package
```

To `jest.config.js` add:
```js
module.exports = {
  preset: require.resolve('jest-puppeteer'),
}
```
To `GooglePage.e2e.test.js` add:
```js
describe('Google', () => {
  beforeAll(async () => {
    await page.goto('https://google.com');
  });

  it('should be titled "Google"', async () => {
    await expect(page.title()).resolves.toMatch('Google');
  });
});
```

Execute:
```sh
$ jest --config=jest.config.js
```

Output:
```
Error: Cannot find module 'jest-puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/Users/pavel/work/OpenSource/GitHub/jest-pupeteer-bug/jest.config.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

## Expected behavior

```bash
 PASS  ./GooglePage.e2e.test.js
  Google
    ✓ should be titled "Google" (5ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.805s, estimated 3s
```

Environment:
```bash
## System:
 - OS: macOS 10.14.3
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 137.36 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
 - Yarn: 1.12.1 - ~/.nvm/versions/node/v10.9.0/bin/yarn
 - npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
```

**Comment by xiaoyuhen** [comment]
hi @R1ZEN 

I have some confusion about your demo. It seems not multiple packages. why did you have two ```package.json```?


If you want to use multiple packages to manage your project, I suggest you use ```lerna``` or ```yarn workspace```. They don't have this problem usually.
