### ISSUE TITLE
Browser closes before next test

### ISSUE THREAD

**Issue by ZiyunHe** [smooth-code/jest-puppeteer#292]
## 🐛 Bug Report

Please help: I have two test files, each file will open a new page in the same browser. 
However, after the first test, the browser will close by itself, and the second test will fail. 

Navigation failed because browser has disconnected!

       9 |       deviceScaleFactor: 1,
      10 |     });
    > 11 |     await page.goto('http://localhost:8887/');
         |                ^
      12 |     await page.waitFor(2000);
      13 |   });
      14 | 

      at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
      at CDPSession._onClosed (node_modules/puppeteer/lib/Connection.js:215:10)
      at Connection._onClose (node_modules/puppeteer/lib/Connection.js:138:15)
      at WebSocketTransport._ws.addEventListener.event (node_modules/puppeteer/lib/WebSocketTransport.js:48:22)
      at WebSocket.onClose (node_modules/ws/lib/event-target.js:124:16)
      at WebSocket.emitClose (node_modules/ws/lib/websocket.js:191:10)
      at Socket.socketOnClose (node_modules/ws/lib/websocket.js:850:15)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.goto (node_modules/puppeteer/lib/Page.js:674:49)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at goto (src/test/cameraShortcut.test.js:11:16)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/regenerator-runtime/runtime.js:145:13
        -- ASYNC --
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at goto (src/test/cameraShortcut.test.js:11:16)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/regenerator-runtime/runtime.js:145:13

Protocol error (Input.dispatchKeyEvent): Session closed. Most likely the page has been closed.

## To Reproduce

run : jest --runInBand

jest-puppeteer.config.js: 
module.exports = {
  launch: {
    headless: false,
    args: [`--window-size=${2500},${1600}`],
  },
};

In the setupFilesAfterEnv: I did jest.setTimeout(300000); 

I also tried with testEnvironment, where I wrote a customed one. 

class CustomEnvironment extends PuppeteerEnvironment {
  async setup() {
    await super.setup();
  }

  teardown() {
    // await super.teardown()  <-------- i commented this out to not close. 
  }
}

## Expected behavior

I don't want the browser to close in between each test cases. 

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
 - CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
 - Memory: 36.03 GB / 62.84 GB
 - Container: Yes
 - Shell: 4.3.48 - /bin/bash
## Binaries:
 - Node: 10.0.0 - ~/.nvm/versions/node/v10.0.0/bin/node
 - Yarn: 1.12.3 - /usr/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v10.0.0/bin/npm
## npmPackages:
 - jest-puppeteer: ^4.3.0 => 4.3.0 

```

**Comment by ZiyunHe** [comment]
oh is it because in my first test i didn't put any "expect" ? (just guessing) 

this is my first test

describe('play bag', () => {
  beforeAll(async () => {
    await page.setViewport({
      width: 2500,
      height: 1600,
      deviceScaleFactor: 1,
    });
    await page.goto('http://localhost:8887/');
    await page.waitFor(2000);
  });

  test('open bag', async () => {
    await page.keyboard.press('b');
    const openBtn = await page.waitForSelector('[data-testid="open"]');
    await openBtn.click();
    await page.waitFor(2000);
  });
});
