### ISSUE TITLE
page.goto("http://localhost:5000") hangs in headless if included within jest syntax

### ISSUE THREAD

**Issue by Snupas** [smooth-code/jest-puppeteer#297]
## 🐛 Bug Report

Every page.goto("http://localhost:5000"), pointing to a local flask server, hangs in headless if included within jest syntax. I know it's not related to puppeteer because when I put the exact same code in an IIFE instead of beforeAll/afterAll it works fine:
```
(async () => {
      browser = await puppeteer.launch({
      executablePath: "/usr/bin/google-chrome",
      headless: true,
      args: [`--window-size=${pageWidth},${pageHeight}`]
    });
    const [currPage] = await browser.pages();
    page = currPage;
    await page.setCacheEnabled(false)
    await page.setViewport({ width,height });
    await page.goto('http://localhost:5000');
})();

```

## To Reproduce

src:
```
const puppeteer = require('puppeteer-core');
const testConfig = require("../utils/testConfig.json");

let browser, page;
const { URLRoot, pageWidth, pageHeight, username, password } = testConfig;
let width = parseInt(pageWidth);
let height = parseInt(pageHeight);
beforeAll(async () => {
      browser = await puppeteer.launch({
      executablePath: "/usr/bin/google-chrome",
      headless: true,
      args: [`--window-size=${pageWidth},${pageHeight}`]
    });
    const [currPage] = await browser.pages();
    page = currPage;
    await page.setCacheEnabled(false)
    await page.setViewport({ width,height });
    await page.goto('http://localhost:5000');
});

  describe('tset', () => {
    it('should display whatever', async () => {
    })
  })

  afterAll(() => {
    browser.close();
  });
  ```
error:
 ```
    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
 ```

## Expected behavior

Go to page, run empty test, exit browser.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

```bash
## System:
 - OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
 - CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
 - Memory: 2.88 GB / 23.30 GB
 - Container: Yes
 - Shell: 5.0.3 - /bin/bash
## Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - Yarn: 1.19.1 - /usr/bin/yarn
 - npm: 6.13.1 - ~/Projects/kelvin/kelvin-web-test/node_modules/.bin/npm
## npmPackages:
 - jest-environment-puppeteer: ^4.3.0 => 4.3.0 
 - jest-puppeteer: ^4.3.0 => 4.3.0 
```

**Comment by MrKickkiller** [comment]
https://stackoverflow.com/questions/59196415/page-goto-hangs-when-using-jest-puppeteer-to-test-a-ruby-on-rails-project

Coincidentally, i'm actually encountering a similar issue, but for a Ruby On Rails project.

```
## System:
 - OS: Linux 5.4 Arch Linux
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 5.38 GB / 15.26 GB
 - Container: Yes
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.13.0 - ~/.nodenv/versions/12.13.0/bin/node
 - Yarn: 1.19.1 - ~/.nodenv/versions/12.13.0/bin/yarn
 - npm: 6.12.0 - ~/.nodenv/versions/12.13.0/bin/npm
## npmPackages:
 - jest-dev-server: ^4.3.0 => 4.3.0 
 - jest-environment-puppeteer: ^4.3.0 => 4.3.0 
 - jest-puppeteer: ^4.3.0 => 4.3.0 
```

**Comment by kienstra** [comment]
Thanks for opening this. Something similar is happening in my local, also:

```bash
TimeoutError: Navigation timeout of 30000 ms exceeded

      at ../../node_modules/puppeteer/lib/LifecycleWatcher.js:101:25
      at FrameManager.navigateFrame (../../node_modules/puppeteer/lib/FrameManager.js:92:21)
      at Frame.goto (../../node_modules/puppeteer/lib/FrameManager.js:376:16)
```

**Comment by monapasan** [comment]
Any idea on how to solve this?
I believe IIFE won't work well with jest

**Comment by Snupas** [comment]
I had some logic that relied on some global variables that were not available in headless mode(namely, window.chrome) and would throw an alert. The alert would prevent all further Puppeteer actions.

I ended up switching to playwright at some point and preloaded a script that would add those missing global variables:
```
 await browserContext.addInitScript({
    path: 'utils/preload.js'
  });
```

The equivalent for puppeteer would probably be using:

**Comment by UziTech** [comment]
is this still an issue?
