### ISSUE TITLE
How can I use "jest-puppeteer.config.js" with "type": "module"?

### ISSUE THREAD

**Issue by stephane-klein** [smooth-code/jest-puppeteer#303]
I am in this example application : [`examples/create-react-app`](https://github.com/smooth-code/jest-puppeteer/tree/master/examples/create-react-app)

When I enable this in my `package.json`:

```
...
  "type": "module",
...
```

I have this error:

```
yarn run v1.19.1
$ jest -c integration/jest.config.json
Determining test suites to run...(node:18974) Warning: require() of ES modules is not supported.
require() of /Users/stephane/Work/github.com/smooth-code/jest-puppeteer/examples/create-react-app/jest-puppeteer.config.js from /Users/stephane/Work/github.com/smooth-code/jest-puppeteer/examples/create-react-app/node_modules/jest-environment-puppeteer/lib/readConfig.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename jest-puppeteer.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/stephane/Work/github.com/smooth-code/jest-puppeteer/examples/create-react-app/package.json.
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/stephane/Work/github.com/smooth-code/jest-puppeteer/examples/create-react-app/jest-puppeteer.config.js
    at Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Object.newLoader [as .js] (/Users/stephane/Work/github.com/smooth-code/jest-puppeteer/examples/create-react-app/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at readConfig (/Users/stephane/Work/github.com/smooth-code/jest-puppeteer/examples/create-react-app/node_modules/jest-environment-puppeteer/lib/readConfig.js:50:29)
    at async setup (/Users/stephane/Work/github.com/smooth-code/jest-puppeteer/examples/create-react-app/node_modules/jest-environment-puppeteer/lib/global.js:19:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How can I fix that?

**Comment by fernandopasik** [comment]
Node 14 and Node 12 now have this unflagged, is there a plan to support this?

**Comment by swissspidy** [comment]
While `jest-puppeteer.config.cjs` is not yet automatically detected/supported, you can set `JEST_PUPPETEER_CONFIG=jest-puppeteer.config.cjs` in the meantime.

**Comment by talentlessguy** [comment]
when trying to use with `ts-jest` and pure ESM I get this:

```js
export default {
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  collectCoverage: true,
  collectCoverageFrom: ['packages/**/src/*.{js,ts}', '!/node_modules/'],
  preset: 'jest-puppeteer',
  globals: {
    'ts-jest': {
      useESM: true
    }
  },
  transform: {
    '^.+\\.(t|j)sx?$': 'ts-jest'
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  resolver: './resolver.cjs',
  modulePathIgnorePatterns: ['examples']
}
```

```
➜ pnpx jest
 FAIL  tests/modal.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/v1rtl/Coding/rainbowkit/packages/modal/tests/modal.test.tsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import puppeteer from 'puppeteer';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/.pnpm/jest-runtime@27.2.4/node_modules/jest-runtime/build/index.js:1723:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.47 s
Ran all test suites.
```
