### ISSUE TITLE
Ignore Errors on page.goto(...)

### ISSUE THREAD

**Issue by kaufmann42** [smooth-code/jest-puppeteer#31]
When I'm running the below code, it errors out due to error messages **on kohls side** that I would like to ignore. For reference, I'm trying to test Chrome extension functionality on other sites so I would need to ignore errors that are not on my own when going to a page.

is there any way to do this?

```js
describe('www.kohls.com user action services', () => {
  beforeEach(async () => {
    await page.goto('https://www.kohls.com');
  });

  it.only('should find nearby stores', async () => {
    const result = await page.evaluate('1 + 2');
    expect(result).toBe(3);
  });
});
```

**Comment by neoziro** [comment]
try catch?

**Comment by kaufmann42** [comment]
After 
```js
beforeEach(async () => {
    try {
      await page.goto('https://www.kohls.com');
    } catch (error) {
      // ignore
    }
  });
```

```bash
yarn run v1.3.2
$ jest src/services/user-action
Determining test suites to run...[0406/095856.990784:ERROR:gpu_process_transport_factory.cc(1008)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:62427/devtools/browser/758b795d-7fc2-4195-b6a4-43a9696ede1a
[0406/095858.772278:INFO:CONSOLE(35)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://s.thebrighttag.co
m/tag?site=QF4SXwN&mode=sync&H=1lm7uu8, is invoked via document.write. The network request for this script MAY be blocked by t
he browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmedin a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://s.btstatic.com/tag.js (35)
[0406/095858.772817:INFO:CONSOLE(35)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://s.thebrighttag.co
m/tag?site=QF4SXwN&mode=sync&H=1lm7uu8, is invoked via document.write. The network request for this script MAY be blocked by t
he browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmedin a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://s.btstatic.com/tag.js (35)
[0406/095858.810375:INFO:CONSOLE(34)] "Uncaught ReferenceError: $omnilinks is not defined", source: https://www.kohls.com/ (34
)
 FAIL  src/services/user-action/kohls-actions.spec.js
  www.kohls.com user action services
    ✕ should find nearby stores (1080ms)
    ○ skipped 5 tests

  ● www.kohls.com user action services › should find nearby stores

    ReferenceError: $omnilinks is not defined

      at HTMLScriptElement.onload (https:/www.kohls.com:34:125)
      at Page._handleException (node_modules/puppeteer/lib/Page.js:409:38)
      at CDPSession.Page.client.on.exception (node_modules/puppeteer/lib/Page.js:102:60)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:217:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:117:19)
      at Receiver._receiver.onmessage (node_modules/ws/lib/WebSocket.js:141:47)
      at Receiver.dataMessage (node_modules/ws/lib/Receiver.js:389:14)
      at Receiver.getData (node_modules/ws/lib/Receiver.js:330:12)
      at Receiver.startLoop (node_modules/ws/lib/Receiver.js:165:16)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 5 skipped, 6 total
Snapshots:   0 total
Time:        1.802s, estimated 4s
Ran all test suites matching /src\/services\/user-action/i.
```

**Comment by neoziro** [comment]
Hmm OK, you should probably ask Puppeteer team about it.

**Comment by neoziro** [comment]
Hmm, nop sorry the problem is here: https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js#L24

This is not configurable for now.

**Comment by neoziro** [comment]
Described in #34

**Comment by bellam** [comment]
great catch and great fix guys.

**Comment by makarim178** [comment]
Thank you for the comments, I was having similar error, and a try catch on the await page.goto('...') solved the issue for me as well. :)
