### ISSUE TITLE
TypeError: Cannot read property 'browserContext' of undefined

### ISSUE THREAD

**Issue by SuAgnes** [smooth-code/jest-puppeteer#379]
Hi, guys. This error will random appear when I running tests.

Chromium opened a tab, but soon automatic shut itself down quickly, then this error appeared.

I didn't find the answer on the google.

1. The error is happens randomly. 
2. Error appear probability is higher of multiple tests running.
3. It won't all fail, often the last test will succeed.
```
 FAIL  __tests__/login/login.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'browserContext' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:161:25)

 FAIL  __tests__/homepage/homepage.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'browserContext' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:161:25)
 
      PASS  __tests__/live/live.test.js (33.217 s)
      Live Room Test Start
      ...
      ...
```

```
jest-puppeteer.config

module.exports = {
  launch: {
    headless: !searchArgv('head'),
    devtools: false,
    // slowMo: 100,
    defaultViewport: {
      width: 1440,
      height: 1080
    },
  },
  browser: 'chromium',
  browserContext: 'default'
};

```

**Comment by MatthiasEngh** [comment]
hi @SuAgnes, which version of jestPuppeteer are you using?

**Comment by kellyjosephprice** [comment]
I'm getting essentially the same error:

```
  ● Test suite failed to run

    TypeError: Cannot read property 'browserContext' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:161:25)
```

```
$ npm ls jest jest-puppeteer puppeteer
...
├── jest@26.4.0 
└── jest-puppeteer@4.4.0
```

Answered my own question, thanks!

**Comment by UziTech** [comment]
is this still an issue?

**Comment by raptoria** [comment]
+1 I'm getting this error, using Typescript

**Comment by raptoria** [comment]
fixed the error by specifying multiple projects in jest :
```
module.exports = {
	projects: [
		{
			displayName: 'automated tests',
			preset: 'jest-puppeteer',
			transform: {
				'\\.tsx?$': 'babel-jest',
				'.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
					'jest-transform-stub'
			},
			moduleNameMapper: {
				'^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
					'jest-transform-stub'
			},
			modulePathIgnorePatterns: ['.next'],
			testMatch: [
				'<rootDir>/src/**/__automated__/**/*.test.ts',
				'<rootDir>/src/**/__automated__/**/*.test.tsx'
			]
		},
		{
			displayName: 'unit/integration tests',
			transform: {
				'\\.tsx?$': 'babel-jest',
				'.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
					'jest-transform-stub'
			},
			moduleNameMapper: {
				'^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
					'jest-transform-stub'
			},
			globalSetup: '<rootDir>/setupEnv.ts',
			setupFilesAfterEnv: ['<rootDir>/setupTests.ts', 'expect-puppeteer'],
			modulePathIgnorePatterns: ['.next'],
			testMatch: [
				'<rootDir>/src/**/__tests_/**/*.test.ts',
				'<rootDir>/src/**/__tests__/**/*.test.tsx'
			]
		}
	]
};

```
