### ISSUE TITLE
Tests fail with UnhandledPromiseRejectionWarning if they connect to imgur.com

### ISSUE THREAD

**Issue by Quelklef** [smooth-code/jest-puppeteer#388]
## Workaround

For other people with the same problem, **a workaround for this issue** is to integrate Jest and Puppeteer [manually](https://jestjs.io/docs/en/puppeteer#custom-example-without-jest-puppeteer-preset) rather than using this preset.

## 🐛 Bug Report

The following test fails:

```
test('weird', async () => {
  await page.goto("https://imgur.com");
  expect(true).toBe(true);
});
```

Stacktrace:
```
λ ~/dev/weird-bug ← npx jest
 FAIL  ./test.js
  ✕ weird (1495 ms)

  ● weird

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.176 s, estimated 3 s
Ran all test suites.
(node:9861) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

Navigation failed because browser has disconnected!
    at /home/lark/dev/gorged/node_modules/puppeteer/src/common/LifecycleWatcher.ts:105:13
    at /home/lark/dev/gorged/node_modules/puppeteer/vendor/mitt/src/index.ts:81:75
    at Array.map (<anonymous>)
    at Object.emit (/home/lark/dev/gorged/node_modules/puppeteer/vendor/mitt/src/index.ts:81:56)
    at CDPSession.emit (/home/lark/dev/gorged/node_modules/puppeteer/src/common/EventEmitter.ts:97:18)
    at CDPSession._onClosed (/home/lark/dev/gorged/node_modules/puppeteer/src/common/Connection.ts:319:10)
    at Connection._onMessage (/home/lark/dev/gorged/node_modules/puppeteer/src/common/Connection.ts:123:17)
    at WebSocket.<anonymous> (/home/lark/dev/gorged/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:41:42)
    at WebSocket.onMessage (/home/lark/dev/gorged/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
(node:9861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Other sites work fine, such as google, reddit, and stackexchange. I'm not sure if there are other sites which exhibit the same behaviour.

Note that this is *not* a problem with Jest timing out, since the failure happens in 2.7s, which is under the 5s Jest timeout.

## To Reproduce

Install Jest, Puppeteer, and jest-puppeteer, and then run the above test suite.

My exact versions are as follows, from `package-lock.json`:
```
jest: 26.6.3
jest-puppeteer: 4.4.0
puppeteer: 8.0.0
```

In desperation, I also tried with a bunch of different versions for Puppeteer, all the way down to 1.0.0. None worked.

## Expected behavior

The test succeeds.

## Link to repl or repo (highly encouraged)

None; provided code is a complete MWE.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 5.8 Pop!_OS 20.10
 - CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
 - Memory: 9.31 GB / 15.44 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 12.18.2 - /usr/bin/node
 - npm: 6.14.8 - /usr/bin/npm
## npmPackages:
 - jest-puppeteer: ^4.4.0 => 4.4.0
```

**Comment by muka** [comment]
I have the same issue and breaks the pipeline.
Maybe catching the error here would make sense ?

https://github.com/smooth-code/jest-puppeteer/blob/53208719c486f7c7f45982a609002b738e9fcd95/packages/jest-environment-puppeteer/src/global.js#L77

**Comment by UziTech** [comment]
@muka if you want to create a PR catching the error in teardown I think that would be acceptable.

**Comment by muka** [comment]
PR #453 open and tested locally with success

**Comment by muka** [comment]
Unfortunately seems this is not fixed. Using in headless I still receive the error

```
(node:9) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

Navigation failed because browser has disconnected!
    at /app/customer-app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:111:13
    at /app/customer-app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
    at Array.map (<anonymous>)
    at Object.emit (/app/customer-app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
    at CDPSession.emit (/app/customer-app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
    at CDPSession._onClosed (/app/customer-app/node_modules/puppeteer/src/common/Connection.ts:340:10)
    at Connection._onMessage (/app/customer-app/node_modules/puppeteer/src/common/Connection.ts:136:17)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at listOnTimeout (internal/timers.js:524:9)
    ```

**Comment by UziTech** [comment]
Should #453 be closed if it doesn't fix this?

**Comment by muka** [comment]
I am using it in CI and seems to work, I would merge thanks

**Comment by muka** [comment]
Thank you! Do you have a schedule for npm release?

**Comment by UziTech** [comment]
I should be able to get a release out later today.

**Comment by UziTech** [comment]
Should be fixed in v6.0.1 🎉

**Comment by IljaKroonen** [comment]
It looks like this fix is causing another crash during teardown in our setup:

```
TypeError: Jest: Got error running globalTeardown - XXX\node_modules\jest-environment-puppeteer\teardown.js, reason: Cannot read property 'catch' of undefined
    at XXX\node_modules\jest-environment-puppeteer\lib\global.js:70:34
    at Array.map (<anonymous>)
    at teardown (XXX\node_modules\jest-environment-puppeteer\lib\global.js:68:30)
    at async XXX\node_modules\@jest\core\build\runGlobalHook.js:125:13
    at async waitForPromiseWithCleanup (XXX\node_modules\@jest\transform\build\ScriptTransformer.js:207:5)
    at async _default (XXX\node_modules\@jest\core\build\runGlobalHook.js:116:9)
    at async runJest (XXX\node_modules\@jest\core\build\runJest.js:405:5)
    at async _run10000 (XXX\node_modules\@jest\core\build\cli\index.js:320:7)
    at async runCLI (XXX\node_modules\@jest\core\build\cli\index.js:173:3)
    at async Object.run (XXX\node_modules\jest\node_modules\jest-cli\build\cli\index.js:155:37)
```

Using puppeteer ^11.0.0 and connecting to a chrome that runs in Docker.

For me, `disconnect()` returns `undefined`

**Comment by muka** [comment]
Hi @IljaKroonen @UziTech 
seems I introduced a bug, PR #456 revert the modification on disconnect. Thank you
