### ISSUE TITLE
Add support for Puppeteer 10

### ISSUE THREAD

**Issue by fregante** [smooth-code/jest-puppeteer#418]
## 🐛 Bug Report

In https://github.com/smooth-code/jest-puppeteer/issues/312 you added support for Firefox and with Puppeteer 9 it seems to work, but with v10 Jest throws this error:

```
Error: Jest: Got error running globalSetup - ./node_modules/jest-environment-puppeteer/setup.js, reason: Could not find expected browser (firefox) locally. Run `PUPPETEER_PRODUCT=firefox npm install` to download a supported Firefox browser binary.
    at FirefoxLauncher.launch (./node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:194:23)
```

I tried deleting `node_modules` and running `PUPPETEER_PRODUCT=firefox npm install puppeteer` as [puppeteer’s docs](https://github.com/puppeteer/puppeteer/blob/v10.0.0/docs/api.md#puppeteerproduct) suggest, but no luck.

It's possible that this is a problem with puppeteer’s installer since after running that `install` command, Chrome was not installed at all and now the regular Chrome run gives me:

```
Error: Jest: Got error running globalSetup - ./node_modules/jest-environment-puppeteer/setup.js, reason: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (884014).
    at ChromeLauncher.launch (./node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:82:27)
```

## To Reproduce

Default config:

```js
// jest-puppeteer.config.js
module.exports = {
	launch: {
		product: 'firefox'
	},
};
```
```js
// package.json
{
  "preset": "jest-puppeteer"
}
```
```js
// test.js
require('expect-puppeteer')

describe('Google', () => {
  beforeAll(async () => {
    await page.goto('https://google.com')
  })

  it('should display "google" text on page', async () => {
    await expect(page).toMatch('google')
  })
})
```
```
PUPPETEER_PRODUCT=firefox npm install --save-dev jest-puppeteer puppeteer jest
npx jest
```

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash

## System:
 - OS: macOS 11.4
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 164.17 MB / 16.00 GB
 - Shell: 3.2.1 - /usr/local/bin/fish
## Binaries:
 - Node: 15.14.0 - /usr/local/bin/node
 - npm: 7.7.6 - /usr/local/bin/npm
## npmPackages:
 - jest-puppeteer: ^5.0.4 => 5.0.4 
```

Running on macOS 11.4, Node 15, latest Chrome and Firefox installed locally.

```
		"jest": "^27.0.4",
		"jest-puppeteer": "^5.0.4",
		"puppeteer": "^10.0.0",
```

**Comment by fregante** [comment]
Closing as I'm not able to install puppeteer v10 anymore 🤔 

```

npm ERR! Found: puppeteer@10.0.0
npm ERR! node_modules/puppeteer
npm ERR!   dev puppeteer@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer puppeteer@">= 1.5.0 < 10" from jest-puppeteer@5.0.4
npm ERR! node_modules/jest-puppeteer
npm ERR!   dev jest-puppeteer@"^5.0.4" from the root project
```

**Comment by fregante** [comment]
Probably a duplicate of https://github.com/puppeteer/puppeteer/issues/7107
