### ISSUE TITLE
TypeError: compilation.getPathWithInfo is not a function

### ISSUE THREAD

**Issue by MaYiFanGitHub** [smooth-code/jest-puppeteer#446]
修改源文件，webapck热更新报错
TypeError: compilation.getPathWithInfo is not a function
    at /Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/webpack/lib/HotModuleReplacementPlugin.js:309:23
    at SyncHook.eval [as call] (eval at create (/Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/@marsjs/cli-template/node_modules/webpack/lib/Compilation.js:1299:37
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>[Jest Dev server] :6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/@marsjs/cli-template/node_modules/webpack/lib/Compilation.js:1242:27)
    at /Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/@marsjs/cli-template/node_modules/webpack/lib/Compiler.js:550:17
    at _done (eval at create (/Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at /Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/@marsjs/cli-template/node_modules/webpack/lib/Compilation.js:1093:12
    at /Users/mayifan02/Desktop/2020.3.3/baidu/medical-fe/med-ui/node_modules/@marsjs/cli-template/node_modu[Jest Dev server] les/webpack/lib/Compilation.js:1005:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by UziTech** [comment]
This seems to be an issue with webpack not jest-puppeteer. What made you think it was an issue with jest-puppeteer?
