### ISSUE TITLE
expect-puppeteer can't use the "page" object -- any "expect" dies with "[object Object] is not supported"

### ISSUE THREAD

**Issue by cinoyter** [smooth-code/jest-puppeteer#495]
## To Reproduce

Using the demo test from the README (slightly modified to absolutely ensure a correct import):

```
import expectPP from 'expect-puppeteer'

describe('Google', () => {
  beforeAll(async () => {
    await page.goto('https://google.com')
  })

  it('should display "google" text on page', async () => {
    await expectPP(page).toMatch('google')
  })
})
```

The test as written fails:

```
  ● Google › should display "google" text on page

    [object Object] is not supported

       7 |
       8 |   it('should display "google" text on page', async () => {
    >  9 |     await expectPP(page).toMatch('google')
         |           ^
      10 |   })
      11 | })

      at expectPuppeteer (node_modules/expect-puppeteer/lib/index.js:105:13)
      at Object.<anonymous> (__tests__/google.js:9:11)
```

I dug in to ``expect-puppeteer/lib/utils.js`` a little bit and expect-puppeteer expects a "Page" object but the object appears to be called "CDPPage". However, I modified getPuppeteerType and getContext to accept "CDPPage" and that does not solve the problem.

## Expected behavior

The test should run as normal using the ``page`` object provided.

## Link to repl or repo (highly encouraged)

https://gitlab.com/simberman/ppexpect_problem

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash

## System:
 - OS: Windows 10 10.0.19043
 - CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
 - Memory: 3.63 GB / 15.93 GB
## Binaries:
 - Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - jest-puppeteer: ^6.1.1 => 6.1.1
```

**Comment by jamesgpearce** [comment]
Same. This is preventing me from updating Puppeteer from 17.1.3 to 18.0.5.

**Comment by swissspidy** [comment]
There are bunch more places that need to be adapted to check for `CDPPage`, such as `getPuppeteerType`. Then it works again.

**Comment by jpreynat** [comment]
This is also preventing us to upgrade `puppeteer` from 17 to 18 or 19.
Any news on this?

**Comment by UziTech** [comment]
I don't know if anyone is working on this right now. If you want to submit a PR it would be much appreciated 😁 👍

**Comment by jpreynat** [comment]
Hi @UziTech 👋 
Actually I just found [this PR](https://github.com/smooth-code/jest-puppeteer/pull/498) that seems to be an attempt at fixing this issue, unless I'm mistaken?

**Comment by UziTech** [comment]
Yes if someone wants to continue that PR and get the tests passing it can be merged.

**Comment by gregberge** [comment]
Please upgrade to v8 and reopen submit a new issue if you experience this problem.

**Comment by jamesgpearce** [comment]
Regressed in #565
