### ISSUE TITLE
Add an option for a dev server to ignore EADDRINUSE

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [smooth-code/jest-puppeteer#69]
I have jest-puppeteer set up with a create-react-app project with the `config.server` option set to start the dev server. This works perfectly in CI 😊.

When locally developing, it's common to separately keep the dev server running in the background to keep a web page open with the latest changes. You then have to remember to close that server before running jest-puppeteer tests. It's not always practical to specify them to run on different ports.

Can the soon-to-be `jest-dev-server` server startup logic have an option to ignore?:

```
Error: listen EADDRINUSE 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1342:14)
    at listenInCluster (net.js:1383:12)
    at doListen (net.js:1498:7)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Emitted 'error' event at:
    at Server.emit (C:\Code\WebClient\node_modules\spdy\lib\spdy\server.js:237:40)
    at emitErrorNT (net.js:1362:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

Side benefit: setup of tests will be faster for not having to start up the dev server.

**Comment by JoshuaKGoldberg** [comment]
Oh, this is in user land. Never mind!
